### ISSUE TITLE
Q: Is it possible to create a dependency resolution dict for aggregated files?

### ISSUE THREAD

**Issue by mr-moon** [fixjs/define.js#10]
Say I wanna put couple of modules into 1 file, is there any way to do that? Like declaring a dict:
```
{
    'core': [
        'utils',
        'i18n',
        'auth'
    ]
}
```

So whenever I ask for `utils`, or `i18n` or `auth` define.js resolves only `core.js` file?

**Comment by mehranhatami** [comment]
@mr-moon if you implement the `core.js` like this:

```javascript
//core.js
define(['utils', 'i18n', 'auth'], function(utils, i18n, auth){
  return {
    utils: utils,
    i18n: i18n,
    auth: auth
  };
});
```
This will provide you with a similar solution like what you said:
> So whenever I ask for utils, or i18n or auth define.js resolves only core.js file?

Do you think this approach will cover what you want?
If NO then I'd be appreciated if you could touch on the differences you have in mind between my solution above and your desired solution, then we could discuss it.

**Comment by Kflash** [comment]
Hi. I see your definination and just wonder. When you load this 3 modules
as mentioned, can they also be used inside a module ( e.g. similar to
requireJS) or it has to be returned first as an object and then used in a
module? And is there any priority on loading this modules? E.g. utils as
number #1 are loaded first, then i!8n or is this true async ?

Anyway. As I see the question, I think his not meaning loading js file
one-by-one, put everyone wrapped in a array, and then loaded. So mixed your
reply Mehran and the question, I more or less think he want to see a
solution like this??

{
    'core': [
        'utils',
        'i18n',
        'auth'
    ]
}

define([ {dict }], function(dict){
  return dict; // Dict is here a object that get returned ( pre-defined I guess)
});


All files inside this 'dict' would then be loaded the normal way,
before wrapped back and returned. Is this correct translation of your
question?

**Comment by mr-moon** [comment]
Thanks for the answers. Sorry for being unclear. My final goal is to get rid of 3 HTTP requests. Suggested solution would of course work, but I'd rather benefit from one request to `core.js` with contents:
```
define('utils', [], function () { ... });
define('i18n', [], function () { ... });
define('auth', [], function () { ... });
```
I have weak knowledge of require.js and r.js specifically, but I suspect I'm pretty much after what it does. The only thing is that I don't want to get final ~10MB concatenated file, I'd rather split it into smaller pieces.

The problem I see is that when project grows large, we can't really afford making 200 requests for separate definitions. We also cannot afford waiting for 10MB single file to be loaded (that's only thing I could achieve with r.js). So I wonder, if we could declare some kind of dictionary:
```
{
    'core':      [   'utils',       'i18n',      'auth'      ],
    'feature-a': [   'def-a-1',     'def-a-2',   'def-a-3'   ],
    'feature-b': [   'def-b-1',     'def-b-2',   'def-b-3'   ],
}
```

And assume code in index.html:
```
define('app', ['def-a-1', 'def-b-2', 'def-b-3'], function (defA1, defB2, defB3) {
    
});
```
And now in order to resolve all those 3 dependencies, `definejs` loads only 2 files: `feature-a.js` and  `feature-b.js`. It's of course not real example, as loading dependencies this way makes not sense, but this illustrates the requirement we have.

Thanks.

**Comment by Kflash** [comment]
@mr-moon this is not possible with todays solution, but @mehranhatami I think you understand what he want?

As I see it this is out of the scoope for requireJS because it's using lazy loading the files, and you want to define a name **app**. 

But it is not hard to fix, but can't this be solved easier with the promise solution of requreJs?

**Comment by mehranhatami** [comment]
@mr-moon I could setup something similar to what you have described which meets your requirements in a way that you could get rid of the 3 HTTP requests.
But in order to do that I have to first come back to my desk :)
Give me couple of hours, I'll implement a new example using DefineJS.

**Comment by mr-moon** [comment]
@mehranhatami wow, thanks. Much appreciated, but there's no rush. I'm exploring the boundaries of lazy-loading. And, to be hones, I have my own implementation of `define()` method, which does almost exactly same thing as `define.js`, but more simplified and lot less advanced. And as of dictionary, I'm currently working on a solution myself. But of course, I'll eager to see how you could play around it. Thanks again.

**Comment by mehranhatami** [comment]
@mr-moon Now you could check out the example: [Dependency Mapping Using DefineJS](https://github.com/fixjs/define.js/tree/master/examples/define-module-mapping).

But like what you had said it needed me to add couple of line to DefineJS to allow users pass a configuration object named: **dependencyMap** in the `config()` call, like:
```javascript
config({
  baseUrl: 'lib-mapped',
  dependencyMap: {
    'core': ['utils', 'i18n', 'auth'],
    'feature-a': ['def-a-1', 'def-a-2', 'def-a-3'],
    'feature-b': ['def-b-1', 'def-b-2', 'def-b-3']
  }
});
```
As it is obvious the **dependencyMap** is exactly what you had called: **a dependency resolution dict for aggregated files**.

The important point here is, this way **DefineJS** allows you to pass the development phase as always. Then in order to build your project use **r.js** like the way I have done it in the [example](https://github.com/fixjs/define.js/blob/master/examples/define-module-mapping/build.sh):
```
./node_modules/requirejs/bin/r.js -o build/core.js
./node_modules/requirejs/bin/r.js -o build/feature-a.js
./node_modules/requirejs/bin/r.js -o build/feature-b.js
```

To have a fear insight of the whole feature, all you need to do is comparing the to html file: [index.html](https://github.com/fixjs/define.js/blob/master/examples/define-module-mapping/index.html) and [index-dev.html](https://github.com/fixjs/define.js/blob/master/examples/define-module-mapping/index-dev.html).

And at the end of the day I have the result as expected with only 3 HTTP requests, without you having to add the script tags to your manually, which means you can have lazy loading even in your built solution.

**Comment by mehranhatami** [comment]
@mr-moon This how it looks like when using the regular AMD style, all the modules get lazy loaded, each with its specific HTTP request:
![dev-mode](https://cloud.githubusercontent.com/assets/6114456/5670801/7719baee-9798-11e4-91e4-166aad1f31e4.png)
And eventually using **DefineJS** even though you have required the `utils` and `auth` modules, but DefineJS lazy loads the main `core.js` file instead. Which ends up only 3 http requests like:
![just3](https://cloud.githubusercontent.com/assets/6114456/5670854/ed388214-9798-11e4-8bfe-66c94f97d31d.png)

By the way to make it easier for you to get started with AMD optimization techniques, I have also come up with 3 build files for your 3 files, you could find them in the [build](https://github.com/fixjs/define.js/tree/master/examples/define-module-mapping/build) folder.

**Comment by mehranhatami** [comment]
@mr-moon this issue is still open for your feedback. Please do let us know of your feedback on the explained solution above.

**Comment by mr-moon** [comment]
WoW thank you very much. This is exactly what I was after!

**Comment by mehranhatami** [comment]
@mr-moon you're welcome. If you take a quick look at the code, you will see that I have added couple lines of code to implement it in DefineJS. But I haven't still added this feature to the README and as far as it is not covered in any release yet you have to get the actual code from Github(no bower or npm) if you are wiling to use it. The next release gets released in couple of days though.

**Comment by mehranhatami** [comment]
@mr-moon I was also wondering if you could let me know if you faced with any bugs or any unforeseen situations, I mean, to make it stable enough for the next version, I probably need to consider some other corner cases as well.

**Comment by mr-moon** [comment]
@mehranhatami I will not be able to heavily use it in near days, but when something pops up I will definitely provide the details. Thanks a lot for the care!
