### ISSUE TITLE
Doesn't resolve the dependencies

### ISSUE THREAD

**Issue by mr-moon** [fixjs/define.js#13]
For some reason I cannot get nested dependencies to be resolved:
http://plnkr.co/edit/kQWKFmceIO1n4ShGJxnm?p=preview

Expected output:

```
resolved | app/exports
resolved | app/component/module
resolved | app/module
resolved | index
```

But getting only

```
resolved | app/exports
```

Other files aren't being requested at all. Maybe I miss something?

**Comment by mehranhatami** [comment]
@mr-moon it is a __DefineJS__ bug which happens when you have different modules with the same name in different directories. In your case you could fix your dependency tree by changing the name of one of the `module.js` files, or wait for me to fix the bug.

**Comment by mr-moon** [comment]
@mehranhatami thanks for the suggested workaround. I'm still sandboxing, evaluating DefineJS to find if it's suitable for use in production, so there's no real need to for a fast fix. Although, yea, I'll be waiting for a fix.

**Comment by Kflash** [comment]
@mehranhatami maybe a good idea to run test cases for definejs too after
ugma to find bugs

**Comment by Kflash** [comment]
@mehranhatami progress on test cases for definejs and ugma? Or can't  I and
the user's of definejs trust you anymore?

**Comment by mehranhatami** [comment]
@KFlash tests are still in progress, all getting rewritten from scratch,
just to make projects more stable. All will be uploaded soon.
