### ISSUE TITLE
Performance gains

### ISSUE THREAD

**Issue by Kflash** [fixjs/define.js#17]
@mehranhatami I think you can get better performance if you put a few guards in important places. As a example say you need to have a string value - validate against A-Z, a-z, before sending it into the function. In that way you can skip the script for further processing on a invalid string value in a early stage.

I see there are lot of places in the code you can do this.

Another optimization method you can do, is avoid looping / iteration where you can. If you iterate an array, check it length first. If length === 1, no need for forEach() or other iteration methods.

Also check for null objects.

You should also throw and stop code on critical places, but do it nicely. Steal my **minErr()** method, and you can give good info back to end-users / end-developers.

**Comment by mehranhatami** [comment]
@Kflash thanks for the advice I am on this issue right now, to see where in the code your advice applies.

**Comment by Kflash** [comment]
@mehranhatami I think it's obvious. Example with iteration.

**Comment by Kflash** [comment]
@mehranhatami Check the comments in your commits: https://github.com/fixjs/define.js/commit/82749214b0f9cafe9df79226c9d8583ca7340c92

**Comment by Kflash** [comment]
@mehranhatami Any prorgess on the tasks you promised to finish 2 weeks ago?
Seems also there is a lot of unsolved tasks from may 2014 until now. Any
progress? You also seems to be very quuet! I think I back out from
everything related to you. Seems like you are not trustwhorty.

**Comment by Kflash** [comment]
@mehranhatami Anything wrong with your email? You stopped reply on emails
I'm sending you. Are you reciving? Or what's going on with you?

**Comment by mehranhatami** [comment]
@Kflash if you have sent me any emails other than this issues, I have to check it and find the problem, I am not getting any email during the last couple of days. let me see if I can find the problem.

**Comment by Kflash** [comment]
@mehranhatami sent you a email yesterday

**Comment by Kflash** [comment]
@mehranhatami Can you try to add Benchmark 2.0 approach too? Needed for ugma

**Comment by Kflash** [comment]
@mehranhatami I close this. The developer  seems  dead
